// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: verification.proto

package verificationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerificationStatus int32

const (
	VerificationStatus_VERIFICATION_STATUS_UNSPECIFIED        VerificationStatus = 0
	VerificationStatus_VERIFICATION_STATUS_VALID              VerificationStatus = 1 // PAN exists
	VerificationStatus_VERIFICATION_STATUS_INVALID            VerificationStatus = 2 // PAN does not exist
	VerificationStatus_VERIFICATION_STATUS_SOURCE_UNAVAILABLE VerificationStatus = 3 // every source failed
)

// Enum value maps for VerificationStatus.
var (
	VerificationStatus_name = map[int32]string{
		0: "VERIFICATION_STATUS_UNSPECIFIED",
		1: "VERIFICATION_STATUS_VALID",
		2: "VERIFICATION_STATUS_INVALID",
		3: "VERIFICATION_STATUS_SOURCE_UNAVAILABLE",
	}
	VerificationStatus_value = map[string]int32{
		"VERIFICATION_STATUS_UNSPECIFIED":        0,
		"VERIFICATION_STATUS_VALID":              1,
		"VERIFICATION_STATUS_INVALID":            2,
		"VERIFICATION_STATUS_SOURCE_UNAVAILABLE": 3,
	}
)

func (x VerificationStatus) Enum() *VerificationStatus {
	p := new(VerificationStatus)
	*p = x
	return p
}

func (x VerificationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VerificationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_verification_proto_enumTypes[0].Descriptor()
}

func (VerificationStatus) Type() protoreflect.EnumType {
	return &file_verification_proto_enumTypes[0]
}

func (x VerificationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VerificationStatus.Descriptor instead.
func (VerificationStatus) EnumDescriptor() ([]byte, []int) {
	return file_verification_proto_rawDescGZIP(), []int{0}
}

type VerifyPANRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ClientId string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Pan      string                 `protobuf:"bytes,2,opt,name=pan,proto3" json:"pan,omitempty"`
	Name     string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Client-supplied idempotency key. Same key returns the same result.
	ReferenceId   string `protobuf:"bytes,4,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyPANRequest) Reset() {
	*x = VerifyPANRequest{}
	mi := &file_verification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPANRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPANRequest) ProtoMessage() {}

func (x *VerifyPANRequest) ProtoReflect() protoreflect.Message {
	mi := &file_verification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPANRequest.ProtoReflect.Descriptor instead.
func (*VerifyPANRequest) Descriptor() ([]byte, []int) {
	return file_verification_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyPANRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *VerifyPANRequest) GetPan() string {
	if x != nil {
		return x.Pan
	}
	return ""
}

func (x *VerifyPANRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VerifyPANRequest) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

type GetVerificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVerificationRequest) Reset() {
	*x = GetVerificationRequest{}
	mi := &file_verification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVerificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVerificationRequest) ProtoMessage() {}

func (x *GetVerificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_verification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVerificationRequest.ProtoReflect.Descriptor instead.
func (*GetVerificationRequest) Descriptor() ([]byte, []int) {
	return file_verification_proto_rawDescGZIP(), []int{1}
}

func (x *GetVerificationRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *GetVerificationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Verification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ReferenceId   string                 `protobuf:"bytes,3,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	PanMasked     string                 `protobuf:"bytes,4,opt,name=pan_masked,json=panMasked,proto3" json:"pan_masked,omitempty"`
	Status        VerificationStatus     `protobuf:"varint,5,opt,name=status,proto3,enum=verification.VerificationStatus" json:"status,omitempty"`
	NameMatch     bool                   `protobuf:"varint,6,opt,name=name_match,json=nameMatch,proto3" json:"name_match,omitempty"`
	Source        string                 `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Verification) Reset() {
	*x = Verification{}
	mi := &file_verification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Verification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Verification) ProtoMessage() {}

func (x *Verification) ProtoReflect() protoreflect.Message {
	mi := &file_verification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Verification.ProtoReflect.Descriptor instead.
func (*Verification) Descriptor() ([]byte, []int) {
	return file_verification_proto_rawDescGZIP(), []int{2}
}

func (x *Verification) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Verification) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Verification) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *Verification) GetPanMasked() string {
	if x != nil {
		return x.PanMasked
	}
	return ""
}

func (x *Verification) GetStatus() VerificationStatus {
	if x != nil {
		return x.Status
	}
	return VerificationStatus_VERIFICATION_STATUS_UNSPECIFIED
}

func (x *Verification) GetNameMatch() bool {
	if x != nil {
		return x.NameMatch
	}
	return false
}

func (x *Verification) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Verification) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_verification_proto protoreflect.FileDescriptor

const file_verification_proto_rawDesc = "" +
	"\n" +
	"\x12verification.proto\x12\fverification\"x\n" +
	"\x10VerifyPANRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x10\n" +
	"\x03pan\x18\x02 \x01(\tR\x03pan\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12!\n" +
	"\freference_id\x18\x04 \x01(\tR\vreferenceId\"E\n" +
	"\x16GetVerificationRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"\x8d\x02\n" +
	"\fVerification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12!\n" +
	"\freference_id\x18\x03 \x01(\tR\vreferenceId\x12\x1d\n" +
	"\n" +
	"pan_masked\x18\x04 \x01(\tR\tpanMasked\x128\n" +
	"\x06status\x18\x05 \x01(\x0e2 .verification.VerificationStatusR\x06status\x12\x1d\n" +
	"\n" +
	"name_match\x18\x06 \x01(\bR\tnameMatch\x12\x16\n" +
	"\x06source\x18\a \x01(\tR\x06source\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt*\xa5\x01\n" +
	"\x12VerificationStatus\x12#\n" +
	"\x1fVERIFICATION_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19VERIFICATION_STATUS_VALID\x10\x01\x12\x1f\n" +
	"\x1bVERIFICATION_STATUS_INVALID\x10\x02\x12*\n" +
	"&VERIFICATION_STATUS_SOURCE_UNAVAILABLE\x10\x032\xb3\x01\n" +
	"\x13VerificationService\x12G\n" +
	"\tVerifyPAN\x12\x1e.verification.VerifyPANRequest\x1a\x1a.verification.Verification\x12S\n" +
	"\x0fGetVerification\x12$.verification.GetVerificationRequest\x1a\x1a.verification.VerificationB7Z5kyc-platform/shared/proto/verification;verificationpbb\x06proto3"

var (
	file_verification_proto_rawDescOnce sync.Once
	file_verification_proto_rawDescData []byte
)

func file_verification_proto_rawDescGZIP() []byte {
	file_verification_proto_rawDescOnce.Do(func() {
		file_verification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_verification_proto_rawDesc), len(file_verification_proto_rawDesc)))
	})
	return file_verification_proto_rawDescData
}

var file_verification_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_verification_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_verification_proto_goTypes = []any{
	(VerificationStatus)(0),        // 0: verification.VerificationStatus
	(*VerifyPANRequest)(nil),       // 1: verification.VerifyPANRequest
	(*GetVerificationRequest)(nil), // 2: verification.GetVerificationRequest
	(*Verification)(nil),           // 3: verification.Verification
}
var file_verification_proto_depIdxs = []int32{
	0, // 0: verification.Verification.status:type_name -> verification.VerificationStatus
	1, // 1: verification.VerificationService.VerifyPAN:input_type -> verification.VerifyPANRequest
	2, // 2: verification.VerificationService.GetVerification:input_type -> verification.GetVerificationRequest
	3, // 3: verification.VerificationService.VerifyPAN:output_type -> verification.Verification
	3, // 4: verification.VerificationService.GetVerification:output_type -> verification.Verification
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_verification_proto_init() }
func file_verification_proto_init() {
	if File_verification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_verification_proto_rawDesc), len(file_verification_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_verification_proto_goTypes,
		DependencyIndexes: file_verification_proto_depIdxs,
		EnumInfos:         file_verification_proto_enumTypes,
		MessageInfos:      file_verification_proto_msgTypes,
	}.Build()
	File_verification_proto = out.File
	file_verification_proto_goTypes = nil
	file_verification_proto_depIdxs = nil
}
