// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: bulk.proto

package bulkpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobStatus int32

const (
	JobStatus_JOB_STATUS_UNSPECIFIED JobStatus = 0
	JobStatus_JOB_STATUS_QUEUED      JobStatus = 1
	JobStatus_JOB_STATUS_RUNNING     JobStatus = 2
	JobStatus_JOB_STATUS_COMPLETED   JobStatus = 3
)

// Enum value maps for JobStatus.
var (
	JobStatus_name = map[int32]string{
		0: "JOB_STATUS_UNSPECIFIED",
		1: "JOB_STATUS_QUEUED",
		2: "JOB_STATUS_RUNNING",
		3: "JOB_STATUS_COMPLETED",
	}
	JobStatus_value = map[string]int32{
		"JOB_STATUS_UNSPECIFIED": 0,
		"JOB_STATUS_QUEUED":      1,
		"JOB_STATUS_RUNNING":     2,
		"JOB_STATUS_COMPLETED":   3,
	}
)

func (x JobStatus) Enum() *JobStatus {
	p := new(JobStatus)
	*p = x
	return p
}

func (x JobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_bulk_proto_enumTypes[0].Descriptor()
}

func (JobStatus) Type() protoreflect.EnumType {
	return &file_bulk_proto_enumTypes[0]
}

func (x JobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobStatus.Descriptor instead.
func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return file_bulk_proto_rawDescGZIP(), []int{0}
}

type BulkItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pan           string                 `protobuf:"bytes,1,opt,name=pan,proto3" json:"pan,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ReferenceId   string                 `protobuf:"bytes,3,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkItem) Reset() {
	*x = BulkItem{}
	mi := &file_bulk_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkItem) ProtoMessage() {}

func (x *BulkItem) ProtoReflect() protoreflect.Message {
	mi := &file_bulk_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkItem.ProtoReflect.Descriptor instead.
func (*BulkItem) Descriptor() ([]byte, []int) {
	return file_bulk_proto_rawDescGZIP(), []int{0}
}

func (x *BulkItem) GetPan() string {
	if x != nil {
		return x.Pan
	}
	return ""
}

func (x *BulkItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BulkItem) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

type CreateJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Items         []*BulkItem            `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateJobRequest) Reset() {
	*x = CreateJobRequest{}
	mi := &file_bulk_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJobRequest) ProtoMessage() {}

func (x *CreateJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bulk_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJobRequest.ProtoReflect.Descriptor instead.
func (*CreateJobRequest) Descriptor() ([]byte, []int) {
	return file_bulk_proto_rawDescGZIP(), []int{1}
}

func (x *CreateJobRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *CreateJobRequest) GetItems() []*BulkItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobRequest) Reset() {
	*x = GetJobRequest{}
	mi := &file_bulk_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequest) ProtoMessage() {}

func (x *GetJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bulk_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequest.ProtoReflect.Descriptor instead.
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return file_bulk_proto_rawDescGZIP(), []int{2}
}

func (x *GetJobRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *GetJobRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Job struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Status        JobStatus              `protobuf:"varint,3,opt,name=status,proto3,enum=bulk.JobStatus" json:"status,omitempty"`
	Total         int32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	Processed     int32                  `protobuf:"varint,5,opt,name=processed,proto3" json:"processed,omitempty"`
	Valid         int32                  `protobuf:"varint,6,opt,name=valid,proto3" json:"valid,omitempty"`
	Invalid       int32                  `protobuf:"varint,7,opt,name=invalid,proto3" json:"invalid,omitempty"`
	Failed        int32                  `protobuf:"varint,8,opt,name=failed,proto3" json:"failed,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_bulk_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_bulk_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_bulk_proto_rawDescGZIP(), []int{3}
}

func (x *Job) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Job) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Job) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_JOB_STATUS_UNSPECIFIED
}

func (x *Job) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Job) GetProcessed() int32 {
	if x != nil {
		return x.Processed
	}
	return 0
}

func (x *Job) GetValid() int32 {
	if x != nil {
		return x.Valid
	}
	return 0
}

func (x *Job) GetInvalid() int32 {
	if x != nil {
		return x.Invalid
	}
	return 0
}

func (x *Job) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *Job) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_bulk_proto protoreflect.FileDescriptor

const file_bulk_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"bulk.proto\x12\x04bulk\"S\n" +
	"\bBulkItem\x12\x10\n" +
	"\x03pan\x18\x01 \x01(\tR\x03pan\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\freference_id\x18\x03 \x01(\tR\vreferenceId\"U\n" +
	"\x10CreateJobRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12$\n" +
	"\x05items\x18\x02 \x03(\v2\x0e.bulk.BulkItemR\x05items\"<\n" +
	"\rGetJobRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"\xf6\x01\n" +
	"\x03Job\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12'\n" +
	"\x06status\x18\x03 \x01(\x0e2\x0f.bulk.JobStatusR\x06status\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\x12\x1c\n" +
	"\tprocessed\x18\x05 \x01(\x05R\tprocessed\x12\x14\n" +
	"\x05valid\x18\x06 \x01(\x05R\x05valid\x12\x18\n" +
	"\ainvalid\x18\a \x01(\x05R\ainvalid\x12\x16\n" +
	"\x06failed\x18\b \x01(\x05R\x06failed\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt*p\n" +
	"\tJobStatus\x12\x1a\n" +
	"\x16JOB_STATUS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11JOB_STATUS_QUEUED\x10\x01\x12\x16\n" +
	"\x12JOB_STATUS_RUNNING\x10\x02\x12\x18\n" +
	"\x14JOB_STATUS_COMPLETED\x10\x032g\n" +
	"\vBulkService\x12.\n" +
	"\tCreateJob\x12\x16.bulk.CreateJobRequest\x1a\t.bulk.Job\x12(\n" +
	"\x06GetJob\x12\x13.bulk.GetJobRequest\x1a\t.bulk.JobB'Z%kyc-platform/shared/proto/bulk;bulkpbb\x06proto3"

var (
	file_bulk_proto_rawDescOnce sync.Once
	file_bulk_proto_rawDescData []byte
)

func file_bulk_proto_rawDescGZIP() []byte {
	file_bulk_proto_rawDescOnce.Do(func() {
		file_bulk_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bulk_proto_rawDesc), len(file_bulk_proto_rawDesc)))
	})
	return file_bulk_proto_rawDescData
}

var file_bulk_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_bulk_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_bulk_proto_goTypes = []any{
	(JobStatus)(0),           // 0: bulk.JobStatus
	(*BulkItem)(nil),         // 1: bulk.BulkItem
	(*CreateJobRequest)(nil), // 2: bulk.CreateJobRequest
	(*GetJobRequest)(nil),    // 3: bulk.GetJobRequest
	(*Job)(nil),              // 4: bulk.Job
}
var file_bulk_proto_depIdxs = []int32{
	1, // 0: bulk.CreateJobRequest.items:type_name -> bulk.BulkItem
	0, // 1: bulk.Job.status:type_name -> bulk.JobStatus
	2, // 2: bulk.BulkService.CreateJob:input_type -> bulk.CreateJobRequest
	3, // 3: bulk.BulkService.GetJob:input_type -> bulk.GetJobRequest
	4, // 4: bulk.BulkService.CreateJob:output_type -> bulk.Job
	4, // 5: bulk.BulkService.GetJob:output_type -> bulk.Job
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_bulk_proto_init() }
func file_bulk_proto_init() {
	if File_bulk_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bulk_proto_rawDesc), len(file_bulk_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bulk_proto_goTypes,
		DependencyIndexes: file_bulk_proto_depIdxs,
		EnumInfos:         file_bulk_proto_enumTypes,
		MessageInfos:      file_bulk_proto_msgTypes,
	}.Build()
	File_bulk_proto = out.File
	file_bulk_proto_goTypes = nil
	file_bulk_proto_depIdxs = nil
}
